cabal-version: 3.0
name:          sasha-vocabulary
version:       0.1.0.0
synopsis:      Game-specific vocabulary for SashaMUD
license:       MIT
author:        Michael Litchard
build-type:    Simple

common shared
  default-language:   GHC2021
  ghc-options:
    -Wall -Wcompat -fwarn-redundant-constraints
    -fwarn-incomplete-uni-patterns -fwarn-tabs
    -fwarn-incomplete-record-updates -fwarn-identities
    -Wno-orphans

  default-extensions:
    DerivingStrategies
    OverloadedStrings
    StrictData

library
  import:          shared
  hs-source-dirs:  src
  exposed-modules:
    SashaVocabulary

  build-depends:
    , base           >=4.7 && <5
    , sasha-grammar
