cabal-version: 3.0
name:          sasha-grammar
version:       0.1.0.0
synopsis:      Language foundation for SashaMUD
license:       MIT
author:        Michael Litchard
build-type:    Simple

common shared
  default-language:   GHC2021
  ghc-options:
    -Wall -Wcompat -fwarn-redundant-constraints
    -fwarn-incomplete-uni-patterns -fwarn-tabs
    -fwarn-incomplete-record-updates -fwarn-identities -Wno-orphans

  default-extensions:
    DeriveAnyClass
    DerivingStrategies
    NoImplicitPrelude
    OverloadedStrings
    StrictData

library
  import:          shared
  hs-source-dirs:  src
  exposed-modules:
    Grammar.Lexer
    Grammar.Parser.Atomics.AtomicsTH
    Grammar.Parser.Atomics.Semantics.Rules.ParseRule
    Grammar.Parser.Atomics.Semantics.Rules.Verbs
    Grammar.Parser.Atomics.Semantics.Verbs.ImplicitStimulus
    Grammar.Parser.Atomics.Verbs
    Grammar.Parser.Composites.Model
    Grammar.Parser.Composites.Rules
    Grammar.Sentence
    SashaGrammar

  build-depends:
    , base                  >=4.7 && <5
    , deepseq
    , Earley
    , hashable
    , megaparsec
    , template-haskell
    , text
    , unordered-containers

executable grammar-tests
  import:         shared
  main-is:        Main.hs
  hs-source-dirs: test
  ghc-options:    -fno-warn-missing-home-modules
  build-depends:
    , base
    , Earley
    , hspec
    , hspec-discover
    , QuickCheck
    , sasha-grammar
    , text
    , unordered-containers
