cabal-version: 3.0
name:          sasha-grammar
version:       0.1.0.0
synopsis:      Language foundation for SashaMUD
license:       MIT
author:        Michael Litchard
build-type:    Simple

common shared
  default-language:   GHC2021
  ghc-options:
    -Wall -Wcompat -fwarn-redundant-constraints
    -fwarn-incomplete-uni-patterns -fwarn-tabs
    -fwarn-incomplete-record-updates -fwarn-identities -Wno-orphans

  default-extensions:
    DeriveAnyClass
    DerivingStrategies
    OverloadedStrings
    StrictData

library
  import:          shared
  hs-source-dirs:  src
  exposed-modules:
    Grammar.Lexer
    SashaGrammar

  build-depends:
    , base        >=4.7 && <5
    , deepseq
    , hashable
    , megaparsec
    , text
