cabal-version: 3.0
name:          sasha
version:       0.1.0.0
synopsis:      SashaMUD engine, API, and server
license:       MIT
author:        Michael Litchard
build-type:    Simple

common shared
  default-language:   GHC2021
  ghc-options:
    -Wall -Wcompat -fwarn-redundant-constraints
    -fwarn-incomplete-uni-patterns -fwarn-tabs
    -fwarn-incomplete-record-updates -fwarn-identities -threaded
    -fno-warn-missing-home-modules -rtsopts -freduction-depth=1000
    -Wno-orphans

  default-extensions:
    AllowAmbiguousTypes
    BlockArguments
    CPP
    DataKinds
    DeriveAnyClass
    DerivingStrategies
    DerivingVia
    DuplicateRecordFields
    LambdaCase
    MultiParamTypeClasses
    NoImplicitPrelude
    OverloadedRecordDot
    OverloadedStrings
    RecordWildCards
    RoleAnnotations
    StrictData
    TemplateHaskell
    TypeApplications
    TypeFamilies
    TypeOperators

library
  import:          shared
  hs-source-dirs:  src
  exposed-modules:
    API.Routes
    API.TSClient
    API.Types
    ConstraintRefinement.Actions
    DSL.Builder
    DSL.Model.EDSL.SashaLambdaDSL
    DSL.Vocabulary
    Engine.ActionDiscovery.Instances
    Engine.ActionDiscovery.Percieve.Look
    Engine.ActionDiscovery.Protocol
    Engine.Evaluators.Player.General
    Engine.Resolution.ActionManagement
    Engine.Resolution.Perception
    Engine.Simulation.Clocks
    Engine.Simulation.SignalNetwork
    Error
    Model.Core
    Model.GID
    Model.RandomPool
    Model.RichText
    Model.WireProtocol
    SashaPrelude
    Server.App
    Server.Authentication
    Server.GameWebSocket
    Server.Log
    Server.Server
    Server.Validator

  build-depends:
    , aeson
    , aeson-typescript
    , async
    , base                      >=4.7 && <5
    , bytestring
    , containers
    , deepseq
    , generic-arbitrary
    , hashable
    , microlens-platform
    , mmorph
    , monad-schedule
    , mtl
    , QuickCheck
    , quickcheck-instances
    , rhine                     >=1.6
    , sasha-grammar
    , servant
    , servant-aeson-typescript
    , servant-server
    , servant-websockets
    , stm
    , text
    , transformers
    , uuid
    , wai
    , warp
    , websockets

executable sasha-client-generator
  import:         shared
  main-is:        ClientGenerator.hs
  hs-source-dirs: app
  build-depends:
    , base
    , sasha
    , text

executable sasha-tests
  import:         shared
  main-is:        Spec.hs
  hs-source-dirs: test src
  cpp-options:    -DTESTING
  other-modules:
    API.Routes
    API.TSClient
    API.Types
    ConstraintRefinement.Actions
    DSL.Builder
    DSL.Model.EDSL.SashaLambdaDSL
    DSL.Vocabulary
    Engine.ActionDiscovery.Instances
    Engine.ActionDiscovery.Percieve.Look
    Engine.ActionDiscovery.Protocol
    Engine.Evaluators.Player.General
    Engine.Resolution.ActionManagement
    Engine.Resolution.Perception
    Engine.Simulation.Clocks
    Engine.Simulation.SignalNetwork
    Error
    JSONSpec
    Model.Core
    Model.GID
    Model.RandomPool
    Model.RichText
    Model.WireProtocol
    SashaPrelude
    Server.App
    Server.Authentication
    Server.GameWebSocket
    Server.Log
    Server.Server
    Server.Validator

  build-depends:
    , aeson
    , aeson-typescript
    , async
    , base                      >=4.7 && <5
    , bytestring
    , containers
    , deepseq
    , generic-arbitrary
    , hashable
    , hspec
    , hspec-core
    , hspec-discover
    , microlens-platform
    , mmorph
    , monad-schedule
    , mtl
    , QuickCheck
    , quickcheck-instances
    , rhine                     >=1.6
    , sasha-grammar
    , servant
    , servant-aeson-typescript
    , servant-server
    , servant-websockets
    , stm
    , text
    , transformers
    , uuid
    , wai
    , warp
    , websockets
