DROP TRIGGER IF EXISTS remove_inactive_tokens ON users;
DROP FUNCTION IF EXISTS remove_inactive_tokens;

DROP TABLE IF EXISTS tokens CASCADE;
DROP TABLE IF EXISTS credentials CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS roles CASCADE;

DROP TYPE IF EXISTS role_name CASCADE;
DROP TYPE IF EXISTS allowed_action CASCADE;
DROP TYPE IF EXISTS account_status CASCADE;
