DROP TRIGGER IF EXISTS remove_inactive_tokens ON users;
DROP FUNCTION IF EXISTS remove_inactive_tokens;

DROP TABLE IF EXISTS tokens CASCADE;
DROP TABLE IF EXISTS credentials CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP SEQUENCE IF EXISTS agent_gid_seq CASCADE;

DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP FUNCTION IF EXISTS resource_actions;

DROP TYPE IF EXISTS role_status CASCADE;
DROP TYPE IF EXISTS action CASCADE;
DROP TYPE IF EXISTS resource CASCADE;
DROP TYPE IF EXISTS account_status CASCADE;
