cabal-version: 3.0
name:          sashamud-server
version:       0.1.0.0
synopsis:      SashaMUD server executable
license:       MIT
author:        Michael Litchard
build-type:    Simple

common shared
  default-language:   GHC2021
  ghc-options:
    -Wall -Wcompat -fwarn-redundant-constraints
    -fwarn-incomplete-uni-patterns -fwarn-tabs
    -fwarn-incomplete-record-updates -fwarn-identities -Wno-orphans

  default-extensions:
    DerivingStrategies
    NoImplicitPrelude
    OverloadedStrings

executable sasha-server
  import:         shared
  main-is:        Main.hs
  hs-source-dirs: app
  build-depends:
    , base            >=4.7 && <5
    , sasha
    , sashamud-world
