cabal-version: 3.0
name:          sashamud-server
version:       0.1.0.0
synopsis:      SashaMUD server executable
license:       MIT
author:        Michael Litchard
build-type:    Simple

common shared
  default-language:   GHC2021
  ghc-options:
    -Wall -Wcompat -fwarn-redundant-constraints
    -fwarn-incomplete-uni-patterns -fwarn-tabs
    -fwarn-incomplete-record-updates -fwarn-identities -Wno-orphans

  default-extensions:
    DerivingStrategies
    ExplicitNamespaces
    NoImplicitPrelude
    OverloadedStrings
    TypeFamilies
    UndecidableInstances

executable sasha-server
  import:         shared
  main-is:        Main.hs
  hs-source-dirs: app
  ghc-options:    -threaded -rtsopts
  build-depends:
    , base            >=4.7 && <5
    , sasha
    , sashamud-world

executable sasha-fake-oidc
  import:         shared
  main-is:        Main.hs
  hs-source-dirs: fake-oidc
  ghc-options:    -threaded -rtsopts
  other-modules:  FakeProvider
  build-depends:
    , base               >=4.7 && <5
    , bytestring
    , containers
    , crypton
    , http-api-data
    , http-client
    , http-types
    , memory
    , postgresql-simple
    , resource-pool
    , sasha
    , servant
    , servant-server
    , text
    , uuid
    , warp

executable sasha-e2e-tests
  import:             shared
  main-is:            Spec.hs
  hs-source-dirs:     test-e2e fake-oidc
  ghc-options:        -threaded -rtsopts
  other-modules:
    FakeProvider
    LoginSpec
    LookAtBallSpec
    LookAtPlayerSpec
    LookWitnessSpec
    RoseSpec
    SeleniumHarness

  build-tool-depends: hspec-discover:hspec-discover
  build-depends:
    , async
    , base                  >=4.7 && <5
    , bytestring
    , containers
    , crypton
    , directory
    , filepath
    , hspec
    , http-api-data
    , http-client
    , http-types
    , memory
    , postgresql-migration
    , postgresql-simple
    , process
    , random
    , resource-pool
    , sasha
    , sashamud-world
    , servant
    , servant-server
    , string-interpolate
    , text
    , time
    , uuid
    , warp
    , webdriver

executable sashamud-integration-tests
  import:         shared
  main-is:        Spec.hs
  hs-source-dirs: test fake-oidc
  ghc-options:    -threaded -rtsopts
  other-modules:
    FakeProvider
    Integration.LoginLogoutSpec

  build-depends:
    , async
    , base                  >=4.7 && <5
    , bytestring
    , containers
    , crypton
    , hspec
    , hspec-discover
    , http-api-data
    , http-client
    , http-types
    , memory
    , microlens-platform
    , postgresql-migration
    , postgresql-simple
    , resource-pool
    , sasha
    , sashamud-world
    , servant
    , servant-client
    , servant-client-core
    , servant-server
    , servant-websockets
    , text
    , time
    , uuid
    , warp
    , websockets
