cabal-version: 3.0
name:          sashamud-server
version:       0.1.0.0
synopsis:      SashaMUD server executable
license:       MIT
author:        Michael Litchard
build-type:    Simple

common shared
  default-language:   GHC2021
  ghc-options:
    -Wall -Wcompat -fwarn-redundant-constraints
    -fwarn-incomplete-uni-patterns -fwarn-tabs
    -fwarn-incomplete-record-updates -fwarn-identities -Wno-orphans

  default-extensions:
    DerivingStrategies
    ExplicitNamespaces
    NoImplicitPrelude
    OverloadedStrings
    TypeFamilies
    UndecidableInstances

executable sasha-server
  import:         shared
  main-is:        Main.hs
  hs-source-dirs: app
  ghc-options:    -threaded -rtsopts
  build-depends:
    , base            >=4.7 && <5
    , sasha
    , sashamud-world

executable sasha-e2e-tests
  import:             shared
  main-is:            Spec.hs
  hs-source-dirs:     test-e2e
  ghc-options:        -threaded -rtsopts
  other-modules:
    LoginSpec
    LookAtBallSpec
    LookAtPlayerSpec
    LookWitnessSpec
    RoseSpec
    SeleniumHarness

  build-tool-depends: hspec-discover:hspec-discover
  build-depends:
    , async
    , base                >=4.7 && <5
    , bytestring
    , directory
    , filepath
    , hspec
    , http-client
    , process
    , random
    , sasha
    , sashamud-world
    , string-interpolate
    , text
    , time
    , warp
    , webdriver

executable sashamud-integration-tests
  import:         shared
  main-is:        Spec.hs
  hs-source-dirs: test
  ghc-options:    -threaded -rtsopts
  other-modules:  Integration.LoginLogoutSpec
  build-depends:
    , async
    , base                 >=4.7 && <5
    , bytestring
    , containers
    , hspec
    , hspec-discover
    , http-client
    , http-types
    , microlens-platform
    , sasha
    , sashamud-world
    , servant-client
    , servant-client-core
    , servant-server
    , servant-websockets
    , text
    , warp
    , websockets
